### ISSUE TITLE
Have some kind of init function

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-beacon-node-client#9]
Because of this:-
https://github.com/Financial-Times/next-beacon-node-client/blob/master/lib/beacon.js#L26

And this:-
https://github.com/Financial-Times/next-beacon-node-client/blob/master/app.js#L6

All apps without `BEACON_URL`s — even those that don't need them fail to start.

**Comment by matthew-andrews** [comment]
Something simple & express-y should do the trick:-

```
var bnc = require('next-beacon-node-client');
var bncInstance = bnc();
```

**Comment by aintgoin2goa** [comment]
Beacon client now returns a noop if there is no beacon_url
